apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: smb-flexvol-installer
  namespace: kube-system
  labels:
    k8s-app: smb
spec:
  selector:
    matchLabels:
      name: smb
  template:
    metadata:
      labels:
        name: smb
    spec:
      containers:
      - name: smb-flexvol-installer
        image: odedia/smb-flexvolume
        imagePullPolicy: Always
        volumeMounts:
        - name: volplugins
          mountPath: /var/volplugins/
        - name: varlog
          mountPath: /var/log/
        - name: jqinstall
          mountPath: /var/local/bin/
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/              
      - name: jqinstall
        hostPath:
          path: /usr/local/bin/
      - name: volplugins
        hostPath:
          path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
          type: DirectoryOrCreate
      nodeSelector:
        beta.kubernetes.io/os: linux
